services:
  wobbly-database:
    container_name: 'wobbly-database'
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_HOST=wobbly-database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=wobbly-user
      - POSTGRES_PASSWORD=wobbly-password
      - POSTGRES_DB=wobbly-database
      - POSTGRES_MODE=disable
    ports:
      - '5432:5432'
    volumes:
      - wobbly-data:/var/lib/postgresql/data

volumes:
  wobbly-data:
