services:
  wobbly-prod-database:
    container_name: 'wobbly-prod-database'
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
    volumes:
      - prod-wobbly-data:/var/lib/postgresql/data

volumes:
  prod-wobbly-data:
